name: Android CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    
    - name: Set up JDK 21
      uses: actions/setup-java@main
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Gradle
      run: ./gradlew app:assembleRelease

    - name: Rename unsigned APK
      run: mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/KTA_Faker.apk

    - name: Upload unsigned APK
      uses: actions/upload-artifact@main
      with:
        name: KTA_Faker.apk
        path: app/build/outputs/apk/release/KTA_Faker.apk