name: Android CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Bước checkout mã nguồn
    - name: Checkout repository
      uses: actions/checkout@v3

    # Thiết lập JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    # Cấp quyền thực thi cho tệp gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    # Xây dựng ứng dụng bằng Gradle
    - name: Build with Gradle
      run: ./gradlew app:assembleRelease

    # Đổi tên tệp APK unsigned
    - name: Rename unsigned APK
      run: mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/KTA_Faker.apk

    # Tải lên artifact APK
    - name: Upload unsigned APK
      uses: actions/upload-artifact@v3
      with:
        name: KTA_Faker.apk
        path: app/build/outputs/apk/release/KTA_Faker.apk
